-- ACY V10.0.1 — Reports only
create table if not exists public.club_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  target_user_id uuid references auth.users(id) on delete cascade,
  target_type text not null default 'member',
  target_id text,
  reason text not null,
  details text,
  status text not null default 'open' check (status in ('open','reviewed','ignored','warned','escalated')),
  moderator_note text,
  created_at timestamptz not null default now(),
  handled_at timestamptz,
  handled_by uuid references auth.users(id) on delete set null
);
create index if not exists idx_club_reports_open on public.club_reports(status,created_at desc);
create index if not exists idx_club_reports_target on public.club_reports(target_user_id,created_at desc);
alter table public.club_reports enable row level security;
drop policy if exists "members create reports" on public.club_reports;
create policy "members create reports"
on public.club_reports for insert to authenticated
with check (reporter_id=auth.uid());
drop policy if exists "members read own reports" on public.club_reports;
create policy "members read own reports"
on public.club_reports for select to authenticated
using (reporter_id=auth.uid());
