-- ACY CLUB PROGRESSION / XP / BADGES
-- Run once in Supabase SQL Editor after club_members.sql and club_events_news.sql.

create table if not exists public.club_xp_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_key text not null,
  xp integer not null,
  created_at timestamptz not null default now(),
  unique(user_id, event_key)
);

alter table public.club_xp_events enable row level security;

drop policy if exists "members can read own xp events" on public.club_xp_events;
create policy "members can read own xp events"
on public.club_xp_events for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "admins can manage xp events" on public.club_xp_events;
create policy "admins can manage xp events"
on public.club_xp_events for all
to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

alter table public.profiles
  add column if not exists discord_connected boolean not null default false;

-- Server-side award function. A zeroed reversible event can become active again.
create or replace function public.award_club_xp(
  p_user_id uuid,
  p_event_key text,
  p_xp integer
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_count integer;
  total_xp integer;
begin
  if p_xp <= 0 then
    return 0;
  end if;

  insert into public.club_xp_events(user_id, event_key, xp)
  values (p_user_id, p_event_key, p_xp)
  on conflict (user_id, event_key)
  do update
    set xp = case
      when public.club_xp_events.xp = 0 then excluded.xp
      else public.club_xp_events.xp
    end
  where public.club_xp_events.xp = 0;

  get diagnostics inserted_count = row_count;

  if inserted_count = 1 then
    update public.profiles
    set xp = coalesce(xp, 0) + p_xp,
        updated_at = now()
    where id = p_user_id;
  end if;

  select coalesce(xp, 0) into total_xp
  from public.profiles
  where id = p_user_id;

  return coalesce(total_xp, 0);
end;
$$;

revoke all on function public.award_club_xp(uuid, text, integer) from public;
grant execute on function public.award_club_xp(uuid, text, integer) to service_role;


-- Remove XP for a reversible connection-state action.
create or replace function public.revoke_club_xp(
  p_user_id uuid,
  p_event_key text,
  p_xp integer
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_count integer;
  total_xp integer;
begin
  if p_xp <= 0 then
    return 0;
  end if;

  -- Keep the event row as a zeroed marker. Reconnecting can restore the
  -- current-state XP, while repeated connect/disconnect cycles never stack XP.
  update public.club_xp_events
  set xp = 0
  where user_id = p_user_id
    and event_key = p_event_key
    and xp > 0;

  get diagnostics deleted_count = row_count;

  if deleted_count = 1 then
    update public.profiles
    set xp = greatest(0, coalesce(xp, 0) - p_xp),
        updated_at = now()
    where id = p_user_id;
  end if;

  select coalesce(xp, 0) into total_xp
  from public.profiles
  where id = p_user_id;

  return coalesce(total_xp, 0);
end;
$$;

revoke all on function public.revoke_club_xp(uuid, text, integer) from public;
grant execute on function public.revoke_club_xp(uuid, text, integer) to service_role;
