-- ACY CLUB PET COMPANION / V6.4
-- Run once in Supabase SQL Editor after club_progression.sql.

create table if not exists public.club_pets (
  user_id uuid primary key references auth.users(id) on delete cascade,
  species text not null,
  name text not null,
  hunger integer not null default 100,
  happiness integer not null default 100,
  energy integer not null default 100,
  pet_xp integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_interaction_at timestamptz not null default now(),
  constraint club_pets_species_check check (species in ('cat','dog','fox','axolotl','dragon','unicorn','penguin','panda','bunny','koala','hamster','turtle','owl','frog','bee')),
  constraint club_pets_name_check check (char_length(trim(name)) between 2 and 18),
  constraint club_pets_hunger_check check (hunger between 0 and 100),
  constraint club_pets_happiness_check check (happiness between 0 and 100),
  constraint club_pets_energy_check check (energy between 0 and 100),
  constraint club_pets_xp_check check (pet_xp >= 0)
);

create table if not exists public.club_pet_daily_actions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action_date date not null default current_date,
  created_at timestamptz not null default now(),
  unique(user_id, action_date)
);

alter table public.club_pets enable row level security;
alter table public.club_pet_daily_actions enable row level security;

drop policy if exists "members can read own pet" on public.club_pets;
create policy "members can read own pet"
on public.club_pets for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "members can read own pet actions" on public.club_pet_daily_actions;
create policy "members can read own pet actions"
on public.club_pet_daily_actions for select
to authenticated
using (user_id = auth.uid());

-- Writes are intentionally handled by security-definer functions so clients
-- cannot simply set hunger, happiness, energy or XP to arbitrary values.
revoke all on public.club_pets from authenticated;
revoke all on public.club_pet_daily_actions from authenticated;

create or replace function public.create_club_pet(
  p_species text,
  p_name text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
  normalized_name text;
begin
  if auth.uid() is null then
    raise exception 'Nicht angemeldet.';
  end if;

  if p_species not in ('cat','dog','fox','axolotl','dragon','unicorn','penguin','panda','bunny','koala','hamster','turtle','owl','frog','bee') then
    raise exception 'Ungültige Tierart.';
  end if;

  normalized_name := btrim(p_name);
  if char_length(normalized_name) < 2 or char_length(normalized_name) > 18 then
    raise exception 'Der Tiername muss 2 bis 18 Zeichen lang sein.';
  end if;

  insert into public.club_pets(user_id, species, name)
  values (auth.uid(), p_species, normalized_name)
  on conflict (user_id) do nothing;

  select jsonb_build_object(
    'user_id', user_id,
    'species', species,
    'name', name,
    'hunger', hunger,
    'happiness', happiness,
    'energy', energy,
    'pet_xp', pet_xp,
    'created_at', created_at,
    'updated_at', updated_at,
    'last_interaction_at', last_interaction_at
  ) into result
  from public.club_pets
  where user_id = auth.uid();

  return result;
end;
$$;

create or replace function public.rename_club_pet(p_name text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_name text;
  result jsonb;
begin
  if auth.uid() is null then raise exception 'Nicht angemeldet.'; end if;
  normalized_name := btrim(p_name);
  if char_length(normalized_name) < 2 or char_length(normalized_name) > 18 then
    raise exception 'Der Tiername muss 2 bis 18 Zeichen lang sein.';
  end if;

  update public.club_pets
  set name = normalized_name, updated_at = now()
  where user_id = auth.uid();

  select jsonb_build_object(
    'user_id', user_id, 'species', species, 'name', name,
    'hunger', hunger, 'happiness', happiness, 'energy', energy,
    'pet_xp', pet_xp, 'created_at', created_at,
    'updated_at', updated_at, 'last_interaction_at', last_interaction_at
  ) into result
  from public.club_pets
  where user_id = auth.uid();

  if result is null then raise exception 'Kein Tier vorhanden.'; end if;
  return result;
end;
$$;

create or replace function public.club_pet_action(p_action text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  p public.club_pets%rowtype;
  now_ts timestamptz := now();
  elapsed_hours numeric;
  new_hunger integer;
  new_happiness integer;
  new_energy integer;
  new_pet_xp integer;
  daily_awarded boolean := false;
  species_label text;
  result jsonb;
begin
  if auth.uid() is null then raise exception 'Nicht angemeldet.'; end if;
  if p_action not in ('feed','play','pet') then raise exception 'Ungültige Aktion.'; end if;

  select * into p
  from public.club_pets
  where user_id = auth.uid()
  for update;

  if p.user_id is null then raise exception 'Bitte zuerst ein Tier adoptieren.'; end if;

  elapsed_hours := greatest(0, extract(epoch from (now_ts - p.last_interaction_at)) / 3600.0);

  -- Gentle decay while the user is away. It never drops below zero.
  new_hunger := greatest(0, p.hunger - floor(elapsed_hours * 3)::integer);
  new_happiness := greatest(0, p.happiness - floor(elapsed_hours * 2)::integer);
  new_energy := greatest(0, p.energy - floor(elapsed_hours * 2)::integer);

  -- Small cooldowns prevent button-spamming from becoming the world's least
  -- exciting exploit.
  if p_action = 'feed' and p.last_interaction_at > now_ts - interval '30 minutes' then
    raise exception 'Dein Tier hat gerade erst gefressen. Versuch es später noch einmal.';
  elsif p_action = 'play' and p.last_interaction_at > now_ts - interval '30 minutes' then
    raise exception 'Dein Tier braucht kurz eine Pause.';
  elsif p_action = 'pet' and p.last_interaction_at > now_ts - interval '10 minutes' then
    raise exception 'Dein Tier genießt die Aufmerksamkeit noch.';
  end if;

  if p_action = 'feed' then
    new_hunger := least(100, new_hunger + 28);
    new_energy := greatest(0, new_energy - 3);
    new_happiness := least(100, new_happiness + 4);
  elsif p_action = 'play' then
    if new_energy < 15 then raise exception 'Dein Tier ist zu müde zum Spielen.'; end if;
    new_happiness := least(100, new_happiness + 22);
    new_energy := greatest(0, new_energy - 15);
    new_hunger := greatest(0, new_hunger - 8);
  elsif p_action = 'pet' then
    new_happiness := least(100, new_happiness + 10);
  end if;

  new_pet_xp := p.pet_xp;

  insert into public.club_pet_daily_actions(user_id, action_date)
  values (auth.uid(), current_date)
  on conflict (user_id, action_date) do nothing;

  if found then
    new_pet_xp := new_pet_xp + 5;
    daily_awarded := true;
    perform public.award_club_xp(auth.uid(), 'pet_care_' || current_date::text, 5);
  end if;

  update public.club_pets
  set hunger = new_hunger,
      happiness = new_happiness,
      energy = new_energy,
      pet_xp = new_pet_xp,
      updated_at = now_ts,
      last_interaction_at = now_ts
  where user_id = auth.uid();

  select jsonb_build_object(
    'user_id', user_id, 'species', species, 'name', name,
    'hunger', hunger, 'happiness', happiness, 'energy', energy,
    'pet_xp', pet_xp, 'created_at', created_at,
    'updated_at', updated_at, 'last_interaction_at', last_interaction_at,
    'daily_xp_awarded', daily_awarded
  ) into result
  from public.club_pets
  where user_id = auth.uid();

  return result;
end;
$$;

revoke all on function public.create_club_pet(text,text) from public;
revoke all on function public.rename_club_pet(text) from public;
revoke all on function public.club_pet_action(text) from public;
grant execute on function public.create_club_pet(text,text) to authenticated;
grant execute on function public.rename_club_pet(text) to authenticated;
grant execute on function public.club_pet_action(text) to authenticated;
