create table if not exists public.club_email_dispatch_log (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  status text not null default 'sent',
  created_at timestamptz not null default now()
);
alter table public.club_email_dispatch_log enable row level security;
drop policy if exists "admins read email dispatch log" on public.club_email_dispatch_log;
create policy "admins read email dispatch log" on public.club_email_dispatch_log
for select to authenticated using(exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
create index if not exists idx_club_email_dispatch_created on public.club_email_dispatch_log(created_at desc);
