create table if not exists public.club_events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  event_date timestamptz not null,
  location text default 'Twitch',
  twitch_url text default 'https://www.twitch.tv/acyjannik',
  image_url text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.club_news (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  published_at timestamptz not null default now(),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.club_events enable row level security;
alter table public.club_news enable row level security;

drop policy if exists "public can read enabled club events" on public.club_events;
create policy "public can read enabled club events" on public.club_events
for select to anon, authenticated using (enabled = true);

drop policy if exists "public can read enabled club news" on public.club_news;
create policy "public can read enabled club news" on public.club_news
for select to anon, authenticated using (enabled = true);

drop policy if exists "admins manage club events" on public.club_events;
create policy "admins manage club events" on public.club_events
for all to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

drop policy if exists "admins manage club news" on public.club_news;
create policy "admins manage club news" on public.club_news
for all to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));


insert into public.club_news (title, body, published_at, enabled)
select 'Willkommen im ACY Club','Der ACY Club ist jetzt live. Mehr Community-Funktionen folgen nach und nach.',now(),true
where not exists (select 1 from public.club_news where title='Willkommen im ACY Club');
