-- ACY CLUB CLIPS
-- Run once in Supabase SQL Editor.

create table if not exists public.club_clips (
  id bigint generated by default as identity primary key,
  title text not null,
  clip_url text not null,
  thumbnail_url text,
  description text,
  category text default 'Fortnite',
  published_at timestamptz not null default now(),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.club_clips enable row level security;

drop policy if exists "public can read enabled clips" on public.club_clips;
create policy "public can read enabled clips"
on public.club_clips for select
to anon, authenticated
using (enabled = true);

drop policy if exists "admins manage clips" on public.club_clips;
create policy "admins manage clips"
on public.club_clips for all
to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

insert into public.club_clips (title, clip_url, thumbnail_url, description, category)
select
  'ACY Clip',
  'https://www.twitch.tv/acyjannik',
  null,
  'Dein nächster Lieblingsclip kommt hier rein.',
  'Fortnite'
where not exists (select 1 from public.club_clips);
