-- ACY CLUB V8.4 — Discord Community Feed
create table if not exists public.club_discord_feed_log (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  dedupe_key text,
  payload jsonb not null default '{}'::jsonb,
  discord_sent boolean not null default false,
  created_at timestamptz not null default now(),
  unique(event_type,dedupe_key)
);

alter table public.club_discord_feed_log enable row level security;

drop policy if exists "admins read discord feed log" on public.club_discord_feed_log;
create policy "admins read discord feed log"
on public.club_discord_feed_log
for select to authenticated
using (exists (
  select 1 from public.admin_users a where a.user_id=auth.uid()
));

create index if not exists idx_club_discord_feed_created
on public.club_discord_feed_log(created_at desc);

create index if not exists idx_club_discord_feed_user_created
on public.club_discord_feed_log(user_id,created_at desc);
