-- ACY CLUB V9.1 — Discord linking
create table if not exists public.discord_presence_links (
  discord_user_id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.discord_presence_links enable row level security;

drop policy if exists "members read own discord link" on public.discord_presence_links;
create policy "members read own discord link"
on public.discord_presence_links for select to authenticated
using (user_id=auth.uid());

create index if not exists idx_discord_presence_links_user
on public.discord_presence_links(user_id);

create table if not exists public.club_game_presence_log (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  discord_user_id text,
  game_id bigint references public.games(id) on delete set null,
  game_name text not null,
  online boolean not null default true,
  detected_at timestamptz not null default now()
);

alter table public.club_game_presence_log enable row level security;

drop policy if exists "members read own game presence log" on public.club_game_presence_log;
create policy "members read own game presence log"
on public.club_game_presence_log for select to authenticated
using (user_id=auth.uid());

drop policy if exists "admins read game presence log" on public.club_game_presence_log;
create policy "admins read game presence log"
on public.club_game_presence_log for select to authenticated
using (exists (
  select 1 from public.admin_users a where a.user_id=auth.uid()
));

create index if not exists idx_game_presence_log_detected
on public.club_game_presence_log(detected_at desc);

create index if not exists idx_game_presence_log_user_detected
on public.club_game_presence_log(user_id, detected_at desc);
