-- ACY CLUB V9.9 — Web Push subscriptions
create table if not exists public.club_push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.club_push_subscriptions enable row level security;

drop policy if exists "members manage own push subscriptions" on public.club_push_subscriptions;
create policy "members manage own push subscriptions"
on public.club_push_subscriptions
for select to authenticated
using(user_id=auth.uid());

create index if not exists idx_push_subscriptions_user
on public.club_push_subscriptions(user_id);

create index if not exists idx_push_subscriptions_updated
on public.club_push_subscriptions(updated_at desc);
