-- ACYJANNIK admin database
-- Run this once in Supabase SQL Editor.
--
-- After creating your first Auth user, insert that user's UUID into admin_users.
-- Example:
-- insert into public.admin_users (user_id) values ('YOUR-AUTH-USER-UUID');

create extension if not exists pgcrypto;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade
);

create table if not exists public.site_settings (
  id boolean primary key default true,
  brand_name text not null default 'ACYJANNIK',
  hero_kicker text not null default 'GAMING · STREAMING · COMMUNITY',
  hero_title text not null default 'ACYJANNIK',
  hero_description text not null default 'Willkommen im digitalen Zuhause von Acyjannik. Streams, Games und der ACY Club an einem Ort.',
  about_text text not null default 'Gaming, Streaming und eine Community, die weit über einen Stream hinausgeht.',
  community_title text not null default 'WELCOME TO THE ACY CLUB',
  community_text text not null default 'Mehr als nur ein Chat. Die Community rund um Acyjannik.',
  hero_image_url text default '/assets/acyjannik-hero.png',
  updated_at timestamptz not null default now()
);

create table if not exists public.social_links (
  id bigint generated by default as identity primary key,
  platform text unique not null,
  label text not null,
  url text not null,
  enabled boolean not null default true,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  name text unique not null,
  description text,
  tag text,
  image_url text,
  featured boolean not null default false,
  sort_order integer not null default 0,
  enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

insert into public.site_settings (id)
values (true)
on conflict (id) do nothing;

insert into public.social_links (platform, label, url, sort_order)
values
  ('twitch', 'Twitch', 'https://www.twitch.tv/acyjannik', 1),
  ('tiktok', 'TikTok', 'https://www.tiktok.com/@acyjannik', 2),
  ('whatsapp', 'WhatsApp', 'https://www.whatsapp.com/channel/0029VazFA8UIXnlmgPliHQ10', 3)
on conflict (platform) do nothing;

insert into public.games (name, description, tag, image_url, featured, sort_order)
values
  ('Fortnite', 'Main Game · Ranked · Community', 'MAIN GAME', null, true, 1),
  ('GTA V', 'Aktuell · Open World · Fun', 'AKTUELL', null, false, 2),
  ('Meccha Chameleon', 'Ab und zu · Variety', 'VARIETY', null, false, 3),
  ('Thick As Thieves', 'Variety · Community · Fun', 'VARIETY', null, false, 4)
on conflict (name) do nothing;


-- Enable RLS
alter table public.admin_users enable row level security;
alter table public.site_settings enable row level security;
alter table public.social_links enable row level security;
alter table public.games enable row level security;

-- Public read policies
drop policy if exists "public can read settings" on public.site_settings;
create policy "public can read settings"
on public.site_settings for select
to anon, authenticated
using (true);

drop policy if exists "public can read social links" on public.social_links;
create policy "public can read social links"
on public.social_links for select
to anon, authenticated
using (enabled = true);

drop policy if exists "public can read games" on public.games;
create policy "public can read games"
on public.games for select
to anon, authenticated
using (enabled = true);

-- Admin access policies
drop policy if exists "admins can read admin_users" on public.admin_users;
create policy "admins can read admin_users"
on public.admin_users for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "admins can write settings" on public.site_settings;
create policy "admins can write settings"
on public.site_settings for all
to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

drop policy if exists "admins can write socials" on public.social_links;
create policy "admins can write socials"
on public.social_links for all
to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

drop policy if exists "admins can write games" on public.games;
create policy "admins can write games"
on public.games for all
to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

-- Note: admin_users itself is intentionally not writable from the client.
-- Add/remove admin user UUIDs in the SQL editor.
