-- ACY CLUB V11 — Twitch profiles, stream attendance, watch points and V18.9 rewards

create table if not exists public.club_twitch_accounts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  twitch_user_id text not null unique,
  login text,
  display_name text,
  profile_image_url text,
  email text,
  access_token text not null,
  refresh_token text not null,
  expires_at timestamptz,
  scopes text[] not null default '{}',
  connected_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_club_twitch_accounts_twitch_user on public.club_twitch_accounts(twitch_user_id);
alter table public.club_twitch_accounts enable row level security;
drop policy if exists "members read own twitch account" on public.club_twitch_accounts;
create policy "members read own twitch account" on public.club_twitch_accounts for select to authenticated using (user_id = auth.uid());

create table if not exists public.club_twitch_stream_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  stream_id text,
  stream_date date not null default current_date,
  started_at timestamptz not null default now(),
  last_heartbeat timestamptz not null default now(),
  ended_at timestamptz,
  active boolean not null default true,
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  created_at timestamptz not null default now()
);

create index if not exists idx_twitch_sessions_user_date on public.club_twitch_stream_sessions(user_id,stream_date,started_at desc);
create index if not exists idx_twitch_sessions_active on public.club_twitch_stream_sessions(active,last_heartbeat desc);
create unique index if not exists idx_twitch_one_active_session_per_user on public.club_twitch_stream_sessions(user_id) where active = true;

alter table public.club_twitch_stream_sessions enable row level security;
drop policy if exists "members read own twitch sessions" on public.club_twitch_stream_sessions;
create policy "members read own twitch sessions" on public.club_twitch_stream_sessions for select to authenticated using (user_id = auth.uid());

create table if not exists public.club_twitch_points (
  user_id uuid primary key references auth.users(id) on delete cascade,
  watch_minutes integer not null default 0,
  watch_points integer not null default 0,
  stream_days integer not null default 0,
  current_stream_streak integer not null default 0,
  best_stream_streak integer not null default 0,
  last_stream_date date,
  first_stream_date date,
  updated_at timestamptz not null default now()
);

alter table public.club_twitch_points enable row level security;
drop policy if exists "members read own twitch points" on public.club_twitch_points;
create policy "members read own twitch points" on public.club_twitch_points for select to authenticated using (user_id = auth.uid());

insert into public.club_quest_catalog(quest_key,cadence,category,title,description,icon,target,reward_xp,enabled)
values
('daily_twitch_watch','daily','twitch','Twitch Watcher','30 Minuten ACYJANNIK live schauen.','🔴',30,25,true),
('weekly_twitch_watch','weekly','twitch','Twitch Stammgast','120 Minuten ACYJANNIK live schauen.','📺',120,100,true),
('weekly_twitch_streak','weekly','twitch','Live-Serie','An 3 aufeinanderfolgenden Stream-Tagen dabei sein.','🔥',3,125,true)
on conflict (quest_key) do update set cadence=excluded.cadence,category=excluded.category,title=excluded.title,description=excluded.description,icon=excluded.icon,target=excluded.target,reward_xp=excluded.reward_xp,enabled=excluded.enabled;

create or replace function public.add_twitch_watch_time(p_user_id uuid,p_minutes integer,p_stream_date date)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare
  current_row public.club_twitch_points%rowtype;
  new_streak integer;
  day_gap integer;
  added_minutes integer := greatest(0,least(coalesce(p_minutes,0),5));
  new_stream_day boolean := false;
  week_start date := date_trunc('week',p_stream_date::timestamp)::date;
  milestone_threshold integer;
  milestone_xp integer;
  inserted_count integer;
  current_xp integer := 0;
begin
  insert into public.club_twitch_points(user_id,watch_minutes,watch_points,stream_days,current_stream_streak,best_stream_streak,last_stream_date,first_stream_date)
  values(p_user_id,0,0,1,1,1,p_stream_date,p_stream_date)
  on conflict(user_id) do nothing;

  select * into current_row from public.club_twitch_points where user_id=p_user_id for update;

  if current_row.last_stream_date is null then
    new_streak := 1;
    new_stream_day := true;
    current_row.stream_days := greatest(1,current_row.stream_days);
    current_row.first_stream_date := p_stream_date;
  elsif p_stream_date > current_row.last_stream_date then
    day_gap := p_stream_date-current_row.last_stream_date;
    new_streak := case when day_gap=1 then current_row.current_stream_streak+1 else 1 end;
    new_stream_day := true;
    current_row.stream_days := current_row.stream_days+1;
  else
    new_streak := current_row.current_stream_streak;
  end if;

  current_row.watch_minutes := current_row.watch_minutes+added_minutes;
  current_row.watch_points := current_row.watch_points+added_minutes;
  current_row.current_stream_streak := new_streak;
  current_row.best_stream_streak := greatest(current_row.best_stream_streak,new_streak);
  current_row.last_stream_date := greatest(coalesce(current_row.last_stream_date,p_stream_date),p_stream_date);
  current_row.updated_at := now();

  update public.club_twitch_points set watch_minutes=current_row.watch_minutes,watch_points=current_row.watch_points,stream_days=current_row.stream_days,current_stream_streak=current_row.current_stream_streak,best_stream_streak=current_row.best_stream_streak,last_stream_date=current_row.last_stream_date,first_stream_date=coalesce(first_stream_date,current_row.first_stream_date),updated_at=now() where user_id=p_user_id;

  if added_minutes>0 then
    insert into public.club_quest_progress(user_id,quest_key,period_start,progress,claimed,updated_at)
    values(p_user_id,'daily_twitch_watch',p_stream_date,least(30,added_minutes),false,now())
    on conflict(user_id,quest_key,period_start) do update set progress=least(30,public.club_quest_progress.progress+excluded.progress),updated_at=now();

    insert into public.club_quest_progress(user_id,quest_key,period_start,progress,claimed,updated_at)
    values(p_user_id,'weekly_twitch_watch',week_start,least(120,added_minutes),false,now())
    on conflict(user_id,quest_key,period_start) do update set progress=least(120,public.club_quest_progress.progress+excluded.progress),updated_at=now();
  end if;

  if new_stream_day then
    insert into public.club_quest_progress(user_id,quest_key,period_start,progress,claimed,updated_at)
    values(p_user_id,'weekly_twitch_streak',week_start,least(3,new_streak),false,now())
    on conflict(user_id,quest_key,period_start) do update set progress=greatest(public.club_quest_progress.progress,least(3,excluded.progress)),updated_at=now();

    insert into public.club_xp_events(user_id,event_key,xp) values(p_user_id,'twitch_stream_day_'||p_stream_date::text,10) on conflict(user_id,event_key) do nothing;
    get diagnostics inserted_count=row_count;
    if inserted_count=1 then update public.profiles set xp=coalesce(xp,0)+10,updated_at=now() where id=p_user_id; end if;
  end if;

  for milestone_threshold,milestone_xp in select * from (values (30,25),(60,50),(120,100),(300,250),(600,500)) as m(threshold,xp) loop
    if current_row.watch_minutes>=milestone_threshold then
      insert into public.club_xp_events(user_id,event_key,xp) values(p_user_id,'twitch_watch_'||milestone_threshold::text,milestone_xp) on conflict(user_id,event_key) do nothing;
      get diagnostics inserted_count=row_count;
      if inserted_count=1 then update public.profiles set xp=coalesce(xp,0)+milestone_xp,updated_at=now() where id=p_user_id; end if;
    end if;
  end loop;

  select coalesce(xp,0) into current_xp from public.profiles where id=p_user_id;
  return jsonb_build_object('watchMinutes',current_row.watch_minutes,'watchPoints',current_row.watch_points,'streamDays',current_row.stream_days,'currentStreak',current_row.current_stream_streak,'bestStreak',current_row.best_stream_streak,'xp',coalesce(current_xp,0));
end;
$$;

revoke all on function public.add_twitch_watch_time(uuid,integer,date) from public;
grant execute on function public.add_twitch_watch_time(uuid,integer,date) to service_role;
