-- ACY CLUB V16.1
-- Notification reliability, Daily-Streak-ready alerts and quest progress hydration.
-- Run once in Supabase SQL Editor.

alter table public.club_notification_preferences
  add column if not exists email_daily_streak boolean not null default true,
  add column if not exists email_quests boolean not null default true,
  add column if not exists push_enabled boolean not null default false;

update public.club_notification_preferences
set email_daily_streak = coalesce(email_daily_streak, true),
    email_quests = coalesce(email_quests, true),
    push_enabled = coalesce(push_enabled, false);

create table if not exists public.club_notification_dispatch_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  event_key text not null,
  created_at timestamptz not null default now(),
  unique(user_id, event_type, event_key)
);

alter table public.club_notification_dispatch_log enable row level security;
drop policy if exists "admins read dispatch log" on public.club_notification_dispatch_log;
create policy "admins read dispatch log" on public.club_notification_dispatch_log for select to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
create index if not exists idx_notification_dispatch_user_type on public.club_notification_dispatch_log(user_id,event_type,created_at desc);

create or replace function public.get_my_notification_preferences() returns jsonb language sql security definer set search_path=public as $$
  select coalesce(to_jsonb(p), '{}'::jsonb) from public.club_notification_preferences p where p.user_id = auth.uid();
$$;

create or replace function public.save_my_notification_preferences(
  p_in_app_enabled boolean, p_email_enabled boolean, p_email_votes boolean, p_email_events boolean,
  p_email_news boolean, p_email_live boolean, p_email_achievements boolean, p_email_direct_messages boolean,
  p_email_spotlight boolean, p_email_rewards boolean, p_email_pet boolean,
  p_email_daily_streak boolean default true, p_email_quests boolean default true
) returns jsonb language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() is null then raise exception 'Nicht angemeldet.'; end if;
  insert into public.club_notification_preferences(user_id,in_app_enabled,email_enabled,email_votes,email_events,email_news,email_live,email_achievements,email_direct_messages,email_spotlight,email_rewards,email_pet,email_daily_streak,email_quests,updated_at)
  values(auth.uid(),p_in_app_enabled,p_email_enabled,p_email_votes,p_email_events,p_email_news,p_email_live,p_email_achievements,p_email_direct_messages,p_email_spotlight,p_email_rewards,p_email_pet,p_email_daily_streak,p_email_quests,now())
  on conflict(user_id) do update set in_app_enabled=excluded.in_app_enabled,email_enabled=excluded.email_enabled,email_votes=excluded.email_votes,email_events=excluded.email_events,email_news=excluded.email_news,email_live=excluded.email_live,email_achievements=excluded.email_achievements,email_direct_messages=excluded.email_direct_messages,email_spotlight=excluded.email_spotlight,email_rewards=excluded.email_rewards,email_pet=excluded.email_pet,email_daily_streak=excluded.email_daily_streak,email_quests=excluded.email_quests,updated_at=now();
  return public.get_my_notification_preferences();
end; $$;
revoke all on function public.get_my_notification_preferences() from public;
revoke all on function public.save_my_notification_preferences(boolean,boolean,boolean,boolean,boolean,boolean,boolean,boolean,boolean,boolean,boolean,boolean,boolean) from public;
grant execute on function public.get_my_notification_preferences() to authenticated;
grant execute on function public.save_my_notification_preferences(boolean,boolean,boolean,boolean,boolean,boolean,boolean,boolean,boolean,boolean,boolean,boolean,boolean) to authenticated;

create or replace function public.get_my_quests() returns jsonb language plpgsql security definer set search_path=public as $$
declare daily jsonb; weekly jsonb; today date := current_date; week_start date := date_trunc('week',current_date)::date;
begin
  if auth.uid() is null then raise exception 'Nicht angemeldet.'; end if;
  select coalesce(jsonb_agg(to_jsonb(q) - 'enabled' order by md5(auth.uid()::text||today::text||q.quest_key) desc),'[]'::jsonb) into daily from (
    select c.quest_key,c.cadence,c.category,c.title,c.description,c.icon,c.target,c.reward_xp,coalesce(p.progress,0) as progress,coalesce(p.claimed,false) as claimed
    from public.club_quest_catalog c left join public.club_quest_progress p on p.user_id=auth.uid() and p.quest_key=c.quest_key and p.period_start=today
    where c.enabled and c.cadence='daily' order by md5(auth.uid()::text||today::text||c.quest_key) desc limit 4
  ) q;
  select coalesce(jsonb_agg(to_jsonb(q) - 'enabled' order by md5(auth.uid()::text||week_start::text||q.quest_key) desc),'[]'::jsonb) into weekly from (
    select c.quest_key,c.cadence,c.category,c.title,c.description,c.icon,c.target,c.reward_xp,coalesce(p.progress,0) as progress,coalesce(p.claimed,false) as claimed
    from public.club_quest_catalog c left join public.club_quest_progress p on p.user_id=auth.uid() and p.quest_key=c.quest_key and p.period_start=week_start
    where c.enabled and c.cadence='weekly' order by md5(auth.uid()::text||week_start::text||c.quest_key) desc limit 4
  ) q;
  return jsonb_build_object('daily',daily,'weekly',weekly,'periods',jsonb_build_object('daily',today,'weekly',week_start));
end; $$;
revoke all on function public.get_my_quests() from public; grant execute on function public.get_my_quests() to authenticated;
