-- ACYJANNIK V17.0 — ACY PET LIFE
-- Run once after deploying V17.0. Safe to run more than once.

alter table public.profiles add column if not exists ac_coins integer not null default 100;
update public.profiles set ac_coins=greatest(0,coalesce(ac_coins,100));

create table if not exists public.club_pet_items (
  id uuid primary key default gen_random_uuid(),
  item_key text unique not null, name text not null, icon text not null default '📦',
  item_type text not null, detail text not null default '', cost integer not null default 0,
  hunger integer not null default 0, happiness integer not null default 0, energy integer not null default 0,
  xp integer not null default 0, enabled boolean not null default true, sort_order integer not null default 0
);

create table if not exists public.club_pet_inventory (
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id uuid not null references public.club_pet_items(id) on delete cascade,
  quantity integer not null default 0, updated_at timestamptz not null default now(),
  primary key(user_id,item_id), constraint pet_inventory_quantity_check check(quantity>=0)
);

create table if not exists public.club_pet_activity_log (
  id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade,
  activity_key text not null, activity_date date not null default (now() at time zone 'Europe/Berlin')::date, created_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb,
  unique(user_id,activity_key,activity_date)
);

alter table public.club_pet_items enable row level security; alter table public.club_pet_inventory enable row level security; alter table public.club_pet_activity_log enable row level security;
drop policy if exists "pet items public read" on public.club_pet_items; create policy "pet items public read" on public.club_pet_items for select to authenticated using(enabled=true);
drop policy if exists "own pet inventory" on public.club_pet_inventory; create policy "own pet inventory" on public.club_pet_inventory for select to authenticated using(user_id=auth.uid());
drop policy if exists "own pet activity" on public.club_pet_activity_log; create policy "own pet activity" on public.club_pet_activity_log for select to authenticated using(user_id=auth.uid());
revoke insert,update,delete on public.club_pet_inventory from authenticated; revoke insert,update,delete on public.club_pet_activity_log from authenticated;

insert into public.club_pet_items(item_key,name,icon,item_type,detail,cost,hunger,happiness,energy,xp,sort_order) values
('snack','ACY Snack','🍪','food','Kleiner Snack für zwischendurch.',10,15,0,0,0,10),
('favorite_food','Lieblingsfutter','🥩','food','Sättigt ordentlich und gibt etwas Laune.',25,35,5,0,0,20),
('treat','Leckerli','🧁','food','Kleiner Luxus für gute Laune.',20,10,15,5,0,30),
('premium_food','Premium-Futter','🍖','food','Große Portion für hungrige Begleiter.',40,55,8,5,2,40),
('energy_drink','Energie-Kick','⚡','boost','Gibt deinem Tier einen kleinen Energieschub.',30,0,0,25,0,50),
('mystery_box','Mystery Box','🎁','box','Eine Überraschung mit seltenen Pet-Rewards.',75,0,0,0,0,60),
('toy_ball','ACY Ball','🎾','toy','Ein Spielzeug für mehr Laune.',35,0,20,0,3,70)
on conflict(item_key) do update set name=excluded.name,icon=excluded.icon,detail=excluded.detail,cost=excluded.cost,hunger=excluded.hunger,happiness=excluded.happiness,energy=excluded.energy,xp=excluded.xp,enabled=true;

-- Existing pets receive a small starter pantry once.
insert into public.club_pet_inventory(user_id,item_id,quantity)
select p.user_id,i.id,3 from public.club_pets p join public.club_pet_items i on i.item_key='snack'
on conflict(user_id,item_id) do nothing;
insert into public.club_pet_inventory(user_id,item_id,quantity)
select p.user_id,i.id,1 from public.club_pets p join public.club_pet_items i on i.item_key='treat'
on conflict(user_id,item_id) do nothing;

-- V17: slower, friendlier decay. Pets no longer die from inactivity.
create or replace function public.get_club_pet() returns jsonb language plpgsql security definer set search_path=public as $$
declare p public.club_pets%rowtype; elapsed numeric; h int; ha int; e int;
begin if auth.uid() is null then raise exception 'Nicht angemeldet.'; end if; select * into p from public.club_pets where user_id=auth.uid(); if p.user_id is null then return null; end if;
elapsed:=greatest(0,extract(epoch from(now()-p.last_interaction_at))/3600.0); h:=greatest(0,p.hunger-floor(elapsed*1)::int); ha:=greatest(0,p.happiness-floor(elapsed*0.5)::int); e:=greatest(0,p.energy-floor(elapsed*0.5)::int);
return jsonb_build_object('user_id',p.user_id,'species',p.species,'name',p.name,'hunger',h,'happiness',ha,'energy',e,'pet_xp',p.pet_xp,'created_at',p.created_at,'updated_at',p.updated_at,'last_interaction_at',p.last_interaction_at); end $$;

create or replace function public.get_pet_life_hub() returns jsonb language plpgsql security definer set search_path=public as $$
declare p jsonb; coins int; today date; items jsonb; shop jsonb; feed_count int; play_count int; pet_count int; groom_count int; sleep_count int; snack_used boolean; paw_used boolean;
begin if auth.uid() is null then raise exception 'Nicht angemeldet.'; end if; p:=public.get_club_pet(); select coalesce(ac_coins,0) into coins from public.profiles where id=auth.uid(); today:=(now() at time zone 'Europe/Berlin')::date;
select coalesce(jsonb_agg(jsonb_build_object('key',i.item_key,'name',i.name,'icon',i.icon,'detail',i.detail,'quantity',inv.quantity) order by i.sort_order),'[]'::jsonb) into items from public.club_pet_inventory inv join public.club_pet_items i on i.id=inv.item_id where inv.user_id=auth.uid() and inv.quantity>0 and i.enabled;
select coalesce(jsonb_agg(jsonb_build_object('key',item_key,'name',name,'icon',icon,'detail',detail,'cost',cost,'hunger',hunger,'happiness',happiness,'energy',energy) order by sort_order),'[]'::jsonb) into shop from public.club_pet_items where enabled and cost>0;
select count(*) filter(where activity_key='feed') ,count(*) filter(where activity_key='play'),count(*) filter(where activity_key='pet'),count(*) filter(where activity_key='groom'),count(*) filter(where activity_key='sleep') into feed_count,play_count,pet_count,groom_count,sleep_count from public.club_pet_activity_log where user_id=auth.uid() and activity_date=today;
return jsonb_build_object('pet',p,'ac_coins',coins,'inventory',items,'shop',shop,'daily_supply_claimed',exists(select 1 from public.club_pet_activity_log where user_id=auth.uid() and activity_key='daily_supply' and activity_date=today),'limits',jsonb_build_object('feed',jsonb_build_object('remaining',greatest(0,3-feed_count)),'play',jsonb_build_object('remaining',greatest(0,2-play_count)),'pet',jsonb_build_object('remaining',greatest(0,3-pet_count)),'groom',jsonb_build_object('remaining',greatest(0,1-groom_count)),'sleep',jsonb_build_object('remaining',greatest(0,1-sleep_count))),'games',jsonb_build_object('snack_hunt',jsonb_build_object('used',exists(select 1 from public.club_pet_activity_log where user_id=auth.uid() and activity_key='snack_hunt' and activity_date=today)),'lucky_paw',jsonb_build_object('used',exists(select 1 from public.club_pet_activity_log where user_id=auth.uid() and activity_key='lucky_paw' and activity_date=today)))); end $$;

create or replace function public.club_pet_action(p_action text) returns jsonb language plpgsql security definer set search_path=public as $$
declare p public.club_pets%rowtype; elapsed numeric; h int;ha int;e int; xp_gain int:=5; v_item_key text; item public.club_pet_items%rowtype; inv public.club_pet_inventory%rowtype; lim int; today date:=(now() at time zone 'Europe/Berlin')::date; result jsonb;
begin if auth.uid() is null then raise exception 'Nicht angemeldet.'; end if; if p_action not in('feed','play','pet','groom','sleep') then raise exception 'Ungültige Pet-Aktion.'; end if; select * into p from public.club_pets where user_id=auth.uid() for update; if p.user_id is null then raise exception 'Bitte zuerst ein Tier adoptieren.'; end if; elapsed:=greatest(0,extract(epoch from(now()-p.last_interaction_at))/3600.0); h:=greatest(0,p.hunger-floor(elapsed*1)::int);ha:=greatest(0,p.happiness-floor(elapsed*.5)::int);e:=greatest(0,p.energy-floor(elapsed*.5)::int);
select count(*) into lim from public.club_pet_activity_log where user_id=auth.uid() and activity_key=p_action and activity_date=today; if (p_action='feed' and lim>=3) or (p_action='play' and lim>=2) or (p_action='pet' and lim>=3) or (p_action='groom' and lim>=1) or (p_action='sleep' and lim>=1) then raise exception 'Für heute ist dieses Pflege-Limit erreicht.'; end if;
if p_action='feed' then v_item_key:='snack'; select * into item from public.club_pet_items where public.club_pet_items.item_key=v_item_key and enabled; select * into inv from public.club_pet_inventory where user_id=auth.uid() and item_id=item.id for update; if inv.quantity is null or inv.quantity<1 then raise exception 'Du hast keinen Snack. Hol dir einen im Tagesvorrat, im Shop oder bei einem Minigame.'; end if; update public.club_pet_inventory set quantity=quantity-1,updated_at=now() where user_id=auth.uid() and item_id=item.id; h:=least(100,h+item.hunger);ha:=least(100,ha+item.happiness);e:=least(100,e+item.energy);
elsif p_action='play' then if e<15 then raise exception 'Dein Tier ist zu müde zum Spielen.'; end if; ha:=least(100,ha+25);e:=greatest(0,e-15);h:=greatest(0,h-8);
elsif p_action='pet' then ha:=least(100,ha+10); elsif p_action='groom' then ha:=least(100,ha+15);e:=least(100,e+10); elsif p_action='sleep' then e:=least(100,e+30);h:=greatest(0,h-3); end if;
insert into public.club_pet_activity_log(user_id,activity_key,activity_date) values(auth.uid(),p_action,today) on conflict do nothing; update public.club_pets set hunger=h,happiness=ha,energy=e,pet_xp=pet_xp+xp_gain,updated_at=now(),last_interaction_at=now() where user_id=auth.uid();
perform public.award_club_xp(auth.uid(),'pet_care_'||current_date::text,5); select jsonb_build_object('user_id',user_id,'species',species,'name',name,'hunger',hunger,'happiness',happiness,'energy',energy,'pet_xp',pet_xp,'last_interaction_at',last_interaction_at) into result from public.club_pets where user_id=auth.uid(); return result; end $$;

create or replace function public.claim_pet_daily_supply() returns jsonb language plpgsql security definer set search_path=public as $$
declare today date:=(now() at time zone 'Europe/Berlin')::date; iid uuid;begin if exists(select 1 from public.club_pet_activity_log where user_id=auth.uid() and activity_key='daily_supply' and activity_date=today) then raise exception 'Der Tagesvorrat wurde heute schon abgeholt.';end if;select id into iid from public.club_pet_items where item_key='snack';insert into public.club_pet_inventory(user_id,item_id,quantity) values(auth.uid(),iid,2) on conflict(user_id,item_id) do update set quantity=club_pet_inventory.quantity+2,updated_at=now();update public.profiles set ac_coins=coalesce(ac_coins,0)+10,updated_at=now() where id=auth.uid();insert into public.club_pet_activity_log(user_id,activity_key,activity_date) values(auth.uid(),'daily_supply',today);return public.get_pet_life_hub()||jsonb_build_object('message','+2 Snacks und +10 AC Coins. 🎁');end $$;

create or replace function public.play_pet_minigame(p_game text) returns jsonb language plpgsql security definer set search_path=public as $$
declare today date:=(now() at time zone 'Europe/Berlin')::date; key text; roll numeric:=random(); reward int:=0; coins int:=0; iid uuid; qty int:=1; label text;begin if p_game not in('snack_hunt','lucky_paw') then raise exception 'Unbekanntes Minigame.';end if; if exists(select 1 from public.club_pet_activity_log where user_id=auth.uid() and activity_key=p_game and activity_date=today) then raise exception 'Dieses Minigame kannst du heute nicht noch einmal spielen.';end if;insert into public.club_pet_activity_log(user_id,activity_key,activity_date,metadata) values(auth.uid(),p_game,today,jsonb_build_object('roll',roll)); if p_game='snack_hunt' then reward:=case when roll<.08 then 5 when roll<.35 then 3 else 1 end; coins:=case when roll<.12 then 15 else 5 end; label:=format('+%s Snacks · +%s AC Coins',reward,coins); key:='snack';else reward:=case when roll<.06 then 3 when roll<.30 then 2 else 1 end; coins:=case when roll<.10 then 50 else 12 end; label:=format('+%s Snacks · +%s AC Coins',reward,coins);key:='snack';end if;select id into iid from public.club_pet_items where item_key=key;insert into public.club_pet_inventory(user_id,item_id,quantity) values(auth.uid(),iid,reward) on conflict(user_id,item_id) do update set quantity=club_pet_inventory.quantity+excluded.quantity,updated_at=now();update public.profiles set ac_coins=coalesce(ac_coins,0)+coins,updated_at=now() where id=auth.uid();return jsonb_build_object('ok',true,'reward_label',label,'hub',public.get_pet_life_hub());end $$;

create or replace function public.open_pet_mystery_box() returns jsonb language plpgsql security definer set search_path=public as $$
declare bid uuid; invqty int; roll numeric:=random(); rewardkey text; qty int; coins int:=0; iid uuid; label text;begin select id into bid from public.club_pet_items where item_key='mystery_box';select quantity into invqty from public.club_pet_inventory where user_id=auth.uid() and item_id=bid for update;if coalesce(invqty,0)<1 then raise exception 'Du hast keine Mystery Box.';end if;update public.club_pet_inventory set quantity=quantity-1,updated_at=now() where user_id=auth.uid() and item_id=bid; if roll<.55 then rewardkey:='snack';qty:=3;label:='+3 Snacks';elsif roll<.78 then rewardkey:='treat';qty:=2;label:='+2 Leckerlis';elsif roll<.93 then rewardkey:='premium_food';qty:=1;label:='+1 Premium-Futter';else coins:=100;label:='+100 AC Coins';end if;if rewardkey is not null then select id into iid from public.club_pet_items where item_key=rewardkey;insert into public.club_pet_inventory(user_id,item_id,quantity) values(auth.uid(),iid,qty) on conflict(user_id,item_id) do update set quantity=club_pet_inventory.quantity+excluded.quantity,updated_at=now();end if;if coins>0 then update public.profiles set ac_coins=coalesce(ac_coins,0)+coins,updated_at=now() where id=auth.uid();end if;return jsonb_build_object('ok',true,'reward_label',label,'hub',public.get_pet_life_hub());end $$;

create or replace function public.buy_pet_item(p_item_key text) returns jsonb language plpgsql security definer set search_path=public as $$
declare item public.club_pet_items%rowtype;begin select * into item from public.club_pet_items where item_key=p_item_key and enabled; if item.id is null then raise exception 'Artikel nicht gefunden.';end if;if item.cost<=0 then raise exception 'Artikel nicht käuflich.';end if;if (select coalesce(ac_coins,0) from public.profiles where id=auth.uid())<item.cost then raise exception 'Nicht genug AC Coins.';end if;update public.profiles set ac_coins=ac_coins-item.cost,updated_at=now() where id=auth.uid();insert into public.club_pet_inventory(user_id,item_id,quantity) values(auth.uid(),item.id,1) on conflict(user_id,item_id) do update set quantity=club_pet_inventory.quantity+1,updated_at=now();return jsonb_build_object('ok',true,'message',item.icon||' '||item.name||' gekauft.','hub',public.get_pet_life_hub());end $$;

revoke all on function public.get_pet_life_hub() from public; revoke all on function public.claim_pet_daily_supply() from public; revoke all on function public.play_pet_minigame(text) from public; revoke all on function public.open_pet_mystery_box() from public; revoke all on function public.buy_pet_item(text) from public; grant execute on function public.get_pet_life_hub() to authenticated; grant execute on function public.claim_pet_daily_supply() to authenticated; grant execute on function public.play_pet_minigame(text) to authenticated; grant execute on function public.open_pet_mystery_box() to authenticated; grant execute on function public.buy_pet_item(text) to authenticated;
