-- ACYJANNIK V17.1 — Pet Life reliability + admin coin grants
-- Run once after deploying V17.1.

-- The V17.0 activity log accidentally made each activity unique per day.
-- That made the intended multi-use daily limits impossible. Remove that
-- uniqueness so feed/play/pet/groom/sleep can be used up to their limits.
do $$
declare c record;
begin
  for c in
    select con.conname
    from pg_constraint con
    where con.conrelid='public.club_pet_activity_log'::regclass
      and con.contype='u'
      and (
        select array_agg(att.attname order by u.ord)
        from unnest(con.conkey) with ordinality as u(attnum,ord)
        join pg_attribute att on att.attrelid=con.conrelid and att.attnum=u.attnum
      ) = array['user_id','activity_key','activity_date']::text[]
  loop
    execute format('alter table public.club_pet_activity_log drop constraint %I',c.conname);
  end loop;
end $$;

create index if not exists club_pet_activity_log_user_action_date_idx
  on public.club_pet_activity_log(user_id,activity_key,activity_date);

-- Admin coin audit trail.
create table if not exists public.club_pet_coin_admin_log (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references auth.users(id) on delete restrict,
  target_user_id uuid not null references auth.users(id) on delete cascade,
  amount integer not null check(amount > 0 and amount <= 100000),
  reason text not null default 'Manuelle Admin-Gutschrift',
  created_at timestamptz not null default now()
);
alter table public.club_pet_coin_admin_log enable row level security;
revoke all on public.club_pet_coin_admin_log from anon,authenticated;

create or replace function public.club_pet_action(p_action text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  p public.club_pets%rowtype;
  elapsed numeric; h int; ha int; e int; xp_gain int:=5;
  v_item_key text; item public.club_pet_items%rowtype; inv public.club_pet_inventory%rowtype;
  lim int; today date:=(now() at time zone 'Europe/Berlin')::date; result jsonb;
  max_daily int;
begin
  if auth.uid() is null then raise exception 'Nicht angemeldet.'; end if;
  if p_action not in('feed','play','pet','groom','sleep') then raise exception 'Ungültige Pet-Aktion.'; end if;
  select * into p from public.club_pets where user_id=auth.uid() for update;
  if p.user_id is null then raise exception 'Bitte zuerst ein Tier adoptieren.'; end if;
  perform pg_advisory_xact_lock(hashtextextended(auth.uid()::text||':pet:'||p_action,0));
  elapsed:=greatest(0,extract(epoch from(now()-p.last_interaction_at))/3600.0);
  h:=greatest(0,p.hunger-floor(elapsed*1)::int);
  ha:=greatest(0,p.happiness-floor(elapsed*.5)::int);
  e:=greatest(0,p.energy-floor(elapsed*.5)::int);
  max_daily:=case p_action when 'feed' then 3 when 'play' then 2 when 'pet' then 3 when 'groom' then 1 when 'sleep' then 1 end;
  select count(*) into lim from public.club_pet_activity_log where user_id=auth.uid() and activity_key=p_action and activity_date=today;
  if lim>=max_daily then raise exception 'Für heute ist dieses Pflege-Limit erreicht. Noch % von % übrig.',greatest(0,max_daily-lim),max_daily; end if;
  if p_action='feed' then
    v_item_key:='snack';
    select * into item from public.club_pet_items where item_key=v_item_key and enabled;
    select * into inv from public.club_pet_inventory where user_id=auth.uid() and item_id=item.id for update;
    if inv.quantity is null or inv.quantity<1 then raise exception 'Kein ACY Snack vorhanden. Hol dir Nachschub im Tagesvorrat, Shop oder Minigame.'; end if;
    update public.club_pet_inventory set quantity=quantity-1,updated_at=now() where user_id=auth.uid() and item_id=item.id;
    h:=least(100,h+item.hunger); ha:=least(100,ha+item.happiness); e:=least(100,e+item.energy);
  elsif p_action='play' then
    if e<15 then raise exception 'Dein Tier ist zu müde zum Spielen.'; end if;
    ha:=least(100,ha+25); e:=greatest(0,e-15); h:=greatest(0,h-8);
  elsif p_action='pet' then
    ha:=least(100,ha+10);
  elsif p_action='groom' then
    ha:=least(100,ha+15); e:=least(100,e+10);
  elsif p_action='sleep' then
    e:=least(100,e+30); h:=greatest(0,h-3);
  end if;
  insert into public.club_pet_activity_log(user_id,activity_key,activity_date,metadata)
    values(auth.uid(),p_action,today,jsonb_build_object('xp',xp_gain));
  update public.club_pets set hunger=h,happiness=ha,energy=e,pet_xp=pet_xp+xp_gain,updated_at=now(),last_interaction_at=now() where user_id=auth.uid();
  perform public.award_club_xp(auth.uid(),'pet_care_'||current_date::text,5);
  select jsonb_build_object('user_id',user_id,'species',species,'name',name,'hunger',hunger,'happiness',happiness,'energy',energy,'pet_xp',pet_xp,'last_interaction_at',last_interaction_at,'daily_action',p_action) into result from public.club_pets where user_id=auth.uid();
  return result;
end $$;

-- Admin-only AC Coin grant. Admins are stored in admin_users, moderators are not enough.
create or replace function public.admin_grant_ac_coins(p_user_id uuid,p_amount integer,p_reason text default 'Manuelle Admin-Gutschrift')
returns jsonb language plpgsql security definer set search_path=public as $$
declare new_balance integer; clean_reason text:=left(coalesce(nullif(trim(p_reason),''),'Manuelle Admin-Gutschrift'),120);
begin
  if auth.uid() is null then raise exception 'Nicht angemeldet.'; end if;
  if not exists(select 1 from public.admin_users where user_id=auth.uid()) then raise exception 'Nur Administratoren dürfen AC Coins gutschreiben.'; end if;
  if p_amount is null or p_amount<1 or p_amount>100000 then raise exception 'Betrag muss zwischen 1 und 100.000 AC Coins liegen.'; end if;
  if not exists(select 1 from auth.users where id=p_user_id) then raise exception 'Mitglied nicht gefunden.'; end if;
  update public.profiles set ac_coins=coalesce(ac_coins,0)+p_amount,updated_at=now() where id=p_user_id returning ac_coins into new_balance;
  if new_balance is null then raise exception 'Profil nicht gefunden.'; end if;
  insert into public.club_pet_coin_admin_log(admin_user_id,target_user_id,amount,reason) values(auth.uid(),p_user_id,p_amount,clean_reason);
  return jsonb_build_object('ok',true,'amount',p_amount,'new_balance',new_balance,'reason',clean_reason);
end $$;
revoke all on function public.admin_grant_ac_coins(uuid,integer,text) from public;
grant execute on function public.admin_grant_ac_coins(uuid,integer,text) to authenticated;

-- Make the game check/insertion robust now that the general activity log allows repeated actions.
create or replace function public.play_pet_minigame(p_game text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare today date:=(now() at time zone 'Europe/Berlin')::date; key text; roll numeric:=random(); reward int:=1; coins int:=0; iid uuid; label text;
begin
  if auth.uid() is null then raise exception 'Nicht angemeldet.'; end if;
  if p_game not in('snack_hunt','lucky_paw') then raise exception 'Unbekanntes Minigame.'; end if;
  perform pg_advisory_xact_lock(hashtextextended(auth.uid()::text||':game:'||p_game,0));
  if exists(select 1 from public.club_pet_activity_log where user_id=auth.uid() and activity_key=p_game and activity_date=today) then raise exception 'Dieses Minigame kannst du heute nicht noch einmal spielen.'; end if;
  insert into public.club_pet_activity_log(user_id,activity_key,activity_date,metadata) values(auth.uid(),p_game,today,jsonb_build_object('roll',roll));
  if p_game='snack_hunt' then
    reward:=case when roll<.08 then 5 when roll<.35 then 3 else 1 end; coins:=case when roll<.12 then 15 else 5 end; label:=format('+%s Snacks · +%s AC Coins',reward,coins); key:='snack';
  else
    reward:=case when roll<.06 then 3 when roll<.30 then 2 else 1 end; coins:=case when roll<.10 then 50 else 12 end; label:=format('+%s Snacks · +%s AC Coins',reward,coins); key:='snack';
  end if;
  select id into iid from public.club_pet_items where item_key=key;
  insert into public.club_pet_inventory(user_id,item_id,quantity) values(auth.uid(),iid,reward) on conflict(user_id,item_id) do update set quantity=club_pet_inventory.quantity+excluded.quantity,updated_at=now();
  update public.profiles set ac_coins=coalesce(ac_coins,0)+coins,updated_at=now() where id=auth.uid();
  return jsonb_build_object('ok',true,'reward_label',label,'hub',public.get_pet_life_hub());
end $$;
