-- ACY CLUB V5.2 — COMMUNITY POLLS
-- Run once in Supabase SQL Editor after the existing Club SQL.

create table if not exists public.club_polls (
  id bigint generated by default as identity primary key,
  question text not null,
  description text,
  active boolean not null default true,
  closes_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint club_poll_question_length check (char_length(trim(question)) between 3 and 180)
);

create table if not exists public.club_poll_options (
  id bigint generated by default as identity primary key,
  poll_id bigint not null references public.club_polls(id) on delete cascade,
  label text not null,
  sort_order integer not null default 0,
  constraint club_poll_option_length check (char_length(trim(label)) between 1 and 100)
);

create table if not exists public.club_poll_votes (
  id bigint generated by default as identity primary key,
  poll_id bigint not null references public.club_polls(id) on delete cascade,
  option_id bigint not null references public.club_poll_options(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(poll_id, user_id)
);

create index if not exists idx_club_polls_active on public.club_polls(active, created_at desc);
create index if not exists idx_club_poll_options_poll on public.club_poll_options(poll_id, sort_order);
create index if not exists idx_club_poll_votes_poll on public.club_poll_votes(poll_id);
create index if not exists idx_club_poll_votes_user on public.club_poll_votes(user_id);

alter table public.club_polls enable row level security;
alter table public.club_poll_options enable row level security;
alter table public.club_poll_votes enable row level security;

drop policy if exists "members can read active polls" on public.club_polls;
create policy "members can read active polls"
on public.club_polls for select
to authenticated
using (active = true);

drop policy if exists "admins manage polls" on public.club_polls;
create policy "admins manage polls"
on public.club_polls for all
to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

drop policy if exists "members can read active poll options" on public.club_poll_options;
create policy "members can read active poll options"
on public.club_poll_options for select
to authenticated
using (
  exists (
    select 1 from public.club_polls p
    where p.id = poll_id and p.active = true
  )
);

drop policy if exists "admins manage poll options" on public.club_poll_options;
create policy "admins manage poll options"
on public.club_poll_options for all
to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

drop policy if exists "members can read own poll votes" on public.club_poll_votes;
create policy "members can read own poll votes"
on public.club_poll_votes for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "members can vote once" on public.club_poll_votes;
create policy "members can vote once"
on public.club_poll_votes for insert
to authenticated
with check (
  user_id = auth.uid()
  and exists (
    select 1 from public.club_polls p
    where p.id = poll_id
      and p.active = true
      and (p.closes_at is null or p.closes_at > now())
  )
  and exists (
    select 1 from public.club_poll_options o
    where o.id = option_id and o.poll_id = poll_id
  )
);

drop policy if exists "admins manage poll votes" on public.club_poll_votes;
create policy "admins manage poll votes"
on public.club_poll_votes for all
to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

-- A vote is worth +5 XP once per poll. The unique vote constraint prevents farming.
create or replace function public.award_poll_vote_xp()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.award_club_xp(
    new.user_id,
    'poll_vote_' || new.poll_id::text,
    5
  );
  return new;
end;
$$;

drop trigger if exists trg_award_poll_vote_xp on public.club_poll_votes;
create trigger trg_award_poll_vote_xp
after insert on public.club_poll_votes
for each row execute function public.award_poll_vote_xp();

-- Realtime lets members see vote counts change without refreshing.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'club_poll_votes'
  ) then
    alter publication supabase_realtime add table public.club_poll_votes;
  end if;
end $$;
