-- ACY CLUB V5.1 — DIRECT MESSAGES
-- Run once in Supabase SQL Editor.
-- Requires existing auth.users, public.profiles, public.club_notifications.

create table if not exists public.club_direct_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  message text not null,
  created_at timestamptz not null default now(),
  constraint club_dm_message_length check (
    char_length(trim(message)) between 1 and 1000
  ),
  constraint club_dm_no_self_message check (sender_id <> recipient_id)
);

create index if not exists idx_club_dm_sender_created
  on public.club_direct_messages(sender_id, created_at desc);

create index if not exists idx_club_dm_recipient_created
  on public.club_direct_messages(recipient_id, created_at desc);

alter table public.club_direct_messages enable row level security;

drop policy if exists "members can read own direct messages" on public.club_direct_messages;
create policy "members can read own direct messages"
on public.club_direct_messages
for select
to authenticated
using (sender_id = auth.uid() or recipient_id = auth.uid());

drop policy if exists "members can send direct messages" on public.club_direct_messages;
create policy "members can send direct messages"
on public.club_direct_messages
for insert
to authenticated
with check (sender_id = auth.uid() and sender_id <> recipient_id);

drop policy if exists "members can delete own sent messages" on public.club_direct_messages;
create policy "members can delete own sent messages"
on public.club_direct_messages
for delete
to authenticated
using (sender_id = auth.uid());

-- Notify the recipient immediately when a DM is sent.
create or replace function public.notify_club_dm()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  sender_name text;
begin
  select coalesce(display_name, username, 'ACY Member')
    into sender_name
  from public.profiles
  where id = new.sender_id;

  insert into public.club_notifications (
    user_id,
    title,
    body,
    notification_type,
    link_url
  )
  values (
    new.recipient_id,
    'Neue Nachricht',
    sender_name || ' hat dir eine Nachricht geschickt.',
    'direct_message',
    '/club-profile.html?dm=' || new.sender_id::text
  );

  return new;
end;
$$;

drop trigger if exists trg_notify_club_dm on public.club_direct_messages;
create trigger trg_notify_club_dm
after insert on public.club_direct_messages
for each row execute function public.notify_club_dm();

-- Live message delivery.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'club_direct_messages'
  ) then
    alter publication supabase_realtime add table public.club_direct_messages;
  end if;
end $$;
