-- ACY CLUB EVENT ATTENDANCE
-- Run once in Supabase SQL Editor after club_events_news.sql and club_progression.sql.

create table if not exists public.club_event_attendance (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.club_events(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(event_id, user_id)
);

alter table public.club_event_attendance enable row level security;

drop policy if exists "members can read event attendance" on public.club_event_attendance;
create policy "members can read event attendance"
on public.club_event_attendance
for select to authenticated
using (true);

drop policy if exists "members can join events" on public.club_event_attendance;
create policy "members can join events"
on public.club_event_attendance
for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "members can leave events" on public.club_event_attendance;
create policy "members can leave events"
on public.club_event_attendance
for delete to authenticated
using (user_id = auth.uid());

drop policy if exists "admins manage event attendance" on public.club_event_attendance;
create policy "admins manage event attendance"
on public.club_event_attendance
for all to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));
