-- ACY CLUB V5.0 — LIVE CHAT
-- Run once in Supabase SQL Editor.
-- Requires the existing `profiles` and `admin_users` tables.

create table if not exists public.club_chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  message text not null,
  created_at timestamptz not null default now(),
  constraint club_chat_message_length check (
    char_length(trim(message)) between 1 and 500
  )
);

create index if not exists idx_club_chat_messages_created
  on public.club_chat_messages(created_at desc);

alter table public.club_chat_messages enable row level security;

drop policy if exists "club members can read chat" on public.club_chat_messages;
create policy "club members can read chat"
on public.club_chat_messages
for select
to authenticated
using (true);

drop policy if exists "club members can send chat" on public.club_chat_messages;
create policy "club members can send chat"
on public.club_chat_messages
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "members can delete own chat" on public.club_chat_messages;
create policy "members can delete own chat"
on public.club_chat_messages
for delete
to authenticated
using (user_id = auth.uid());

drop policy if exists "admins can moderate chat" on public.club_chat_messages;
create policy "admins can moderate chat"
on public.club_chat_messages
for delete
to authenticated
using (
  exists (
    select 1 from public.admin_users a
    where a.user_id = auth.uid()
  )
);

-- Optional moderation foundation: admins can temporarily ban members from chat.
create table if not exists public.club_chat_bans (
  user_id uuid primary key references auth.users(id) on delete cascade,
  banned_until timestamptz,
  reason text,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

alter table public.club_chat_bans enable row level security;

drop policy if exists "members can read own chat ban" on public.club_chat_bans;
create policy "members can read own chat ban"
on public.club_chat_bans
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "admins manage chat bans" on public.club_chat_bans;
create policy "admins manage chat bans"
on public.club_chat_bans
for all
to authenticated
using (
  exists (
    select 1 from public.admin_users a
    where a.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.admin_users a
    where a.user_id = auth.uid()
  )
);

-- Server-side anti-spam and ban enforcement.
create or replace function public.enforce_club_chat_rules()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  active_ban timestamptz;
begin
  select banned_until
    into active_ban
  from public.club_chat_bans
  where user_id = new.user_id;

  if active_ban is null then
    -- no active ban
  elsif active_ban > now() then
    raise exception 'CHAT_BANNED';
  else
    delete from public.club_chat_bans
    where user_id = new.user_id
      and banned_until <= now();
  end if;

  if exists (
    select 1
    from public.club_chat_messages
    where user_id = new.user_id
      and created_at > now() - interval '2 seconds'
  ) then
    raise exception 'CHAT_RATE_LIMIT';
  end if;

  new.message := btrim(new.message);
  return new;
end;
$$;

drop trigger if exists trg_enforce_club_chat_rules on public.club_chat_messages;
create trigger trg_enforce_club_chat_rules
before insert on public.club_chat_messages
for each row execute function public.enforce_club_chat_rules();

-- Realtime: make chat inserts/deletes stream to connected members.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'club_chat_messages'
  ) then
    alter publication supabase_realtime add table public.club_chat_messages;
  end if;
end $$;
