-- ACY CLUB ACHIEVEMENTS + LEADERBOARD
-- Run once in Supabase SQL Editor after the existing club tables.

create table if not exists public.club_achievements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  achievement_key text not null,
  awarded_at timestamptz not null default now(),
  unique(user_id, achievement_key)
);

alter table public.club_achievements enable row level security;

drop policy if exists "members can read own achievements" on public.club_achievements;
create policy "members can read own achievements"
on public.club_achievements
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "members can read leaderboard achievements" on public.club_achievements;
create policy "members can read leaderboard achievements"
on public.club_achievements
for select
to authenticated
using (true);

drop policy if exists "admins manage achievements" on public.club_achievements;
create policy "admins manage achievements"
on public.club_achievements
for all
to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

-- Seed/refresh the base rookie achievement for existing profiles.
insert into public.club_achievements (user_id, achievement_key)
select id, 'acy_rookie'
from public.profiles
where not exists (
  select 1
  from public.club_achievements a
  where a.user_id = public.profiles.id
    and a.achievement_key = 'acy_rookie'
);
