-- ACY CLUB V3.9
-- Notifications + Community Spotlight
-- Run once in Supabase SQL Editor.

create table if not exists public.club_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  body text not null,
  notification_type text not null default 'general',
  link_url text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.club_notifications enable row level security;

drop policy if exists "members can read own notifications" on public.club_notifications;
create policy "members can read own notifications"
on public.club_notifications
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "members can update own notifications" on public.club_notifications;
create policy "members can update own notifications"
on public.club_notifications
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "admins manage notifications" on public.club_notifications;
create policy "admins manage notifications"
on public.club_notifications
for all
to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

create table if not exists public.club_spotlight (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'Member of the Month',
  blurb text,
  month_key text unique not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.club_spotlight enable row level security;

drop policy if exists "members can read enabled spotlight" on public.club_spotlight;
create policy "members can read enabled spotlight"
on public.club_spotlight
for select
to anon, authenticated
using (enabled = true);

drop policy if exists "admins manage spotlight" on public.club_spotlight;
create policy "admins manage spotlight"
on public.club_spotlight
for all
to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));
